spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/mstock
    username: bakali
    password: bakali
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
server:
  port: 8080
